# Generated by Django 6.0.5 on 2026-05-12 07:30

import sqlalchemy.sql.elements
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='image',
            field=models.CharField(default=sqlalchemy.sql.elements.Null, max_length=100),
        ),
    ]
