# Generated by Django 6.0.5 on 2026-05-12 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='cover',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
